### ISSUE TITLE
A Thanks Message

### ISSUE THREAD

**Issue by onuratakan** [Nanguage/oneFace#3]
Hello, i am Onur, i am a CTO of a community that develop Blockchain based Decentralized Application Network. This repository have a very good idea. All contributor of this project and me should develop this project and use in the other project. Let's not stop developing.

Onur Atakan ULUSOY - CTO of Decentra Network Community

**Comment by Nanguage** [comment]
Thank you for your appreciation, we can develop oneFace together.
